version: "3.3"
services:
    rabbitmq:
        container_name: "rabbitmq"
        image: rabbitmq:3.8-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=django_api
            - RABBITMQ_DEFAULT_PASS=343877
        ports:
            - '5672:5672'
            - '15672:15672'

    admin_api:
        container_name: "admin_api"
        image: malyyigor34/15_minute_admin_api
        ports:
            - "8111:8000"
        environment:
            - PIKA_USERNAME=django_api
            - PIKA_PASSWORD=343877
            - PIKA_HOST=rabbitmq
            - PIKA_PORT=5672
        depends_on:
            db:
                condition: service_started
            rabbitmq:
                condition: service_started

    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3306:3306'
        volumes:
            - my-db:/var/lib/mysql

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 343877
        ports:
            - "27017:27017"

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: 343877
            ME_CONFIG_MONGODB_URL: mongodb://root:343877@mongo:27017/

volumes:
  my-db:

#TODO jenkins pipeline
#TODO tests for django api views
#TODO django logs
#TODO create env file