# Generated by Django 4.2.5 on 2023-12-04 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('finish_date', models.DateTimeField(blank=True, default=None, null=True, unique=True)),
                ('items_collected', models.IntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openstreetmaps.task')),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=800)),
                ('date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=260)),
                ('task_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openstreetmaps.taskresult')),
            ],
        ),
    ]
