# Generated by Django 4.2.5 on 2023-12-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openstreetmaps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Error',
            new_name='OSMError',
        ),
        migrations.RenameModel(
            old_name='Task',
            new_name='OSMTask',
        ),
        migrations.RenameModel(
            old_name='TaskResult',
            new_name='OSMTaskResult',
        ),
    ]
